[[tcxHap_prebuilt_jll]]
git-tree-sha1 = "20a3debc41edbc51e2cd65dbb81401cb38579b30"
os = "macos"
arch = "aarch64"

    [[tcxHap_prebuilt_jll.download]]
    sha256 = "4394b0c1c698a7c885303d73b61c8cd414cfb890e7c1460f31895dedc094cf7c"
    url = "https://github.com/funatsufumiya/tcxHap_prebuilt_jll_packager.jl/releases/download/v0.1.0/macos-aarch64.tar.gz"

[[tcxHap_prebuilt_jll]]
git-tree-sha1 = "2346fc78eb98b7999a072513bfd5136f15ffc776"
os = "linux"
arch = "x86_64"

    [[tcxHap_prebuilt_jll.download]]
    sha256 = "03ab221110bfbaa5e502339be530506bdd04a99bd5c3642bde32738010b111fc"
    url = "https://github.com/funatsufumiya/tcxHap_prebuilt_jll_packager.jl/releases/download/v0.1.0/linux-x86_64.tar.gz"

[[tcxHap_prebuilt_jll]]
git-tree-sha1 = "510c39d2ef73a45d5f5de1398bc54555ee5e34ba"
os = "windows"
arch = "x86_64"

    [[tcxHap_prebuilt_jll.download]]
    sha256 = "25cec8525d41854facdd8f0b22781a2662f56093af744a04cd44b7e80f6f1c5e"
    url = "https://github.com/funatsufumiya/tcxHap_prebuilt_jll_packager.jl/releases/download/v0.1.0/windows-x86_64.tar.gz"