[[tcxHap_prebuilt_jll]]
git-tree-sha1 = "bd776f6567342e4b72e4f52cddfeb905067fd67f"
os = "macos"
arch = "aarch64"

    [[tcxHap_prebuilt_jll.download]]
    sha256 = "f444cbd3a55b5ae9c324220e0f0d45329cd6572aeec7131d141478b90de8fffc"
    url = "https://github.com/funatsufumiya/tcxHap_prebuilt_jll_packager.jl/releases/download/v0.1.0/macos-aarch64.tar.gz"

[[tcxHap_prebuilt_jll]]
git-tree-sha1 = "ee1f9ccf8eb387e18e9bd5de8bd7b7d4f922be3a"
os = "linux"
arch = "x86_64"

    [[tcxHap_prebuilt_jll.download]]
    sha256 = "2a1bf3b7c7751b33cc63cdb3570c03953468ab38ec9188d8ddb2e3e067f756f3"
    url = "https://github.com/funatsufumiya/tcxHap_prebuilt_jll_packager.jl/releases/download/v0.1.0/linux-x86_64.tar.gz"

[[tcxHap_prebuilt_jll]]
git-tree-sha1 = "f879006f57ac7432fd7c5df4e704e070d0d87d43"
os = "windows"
arch = "x86_64"

    [[tcxHap_prebuilt_jll.download]]
    sha256 = "3ed6d207e2353dfa664214e380ea1498256897511f4254f487d86c226bc3ea8e"
    url = "https://github.com/funatsufumiya/tcxHap_prebuilt_jll_packager.jl/releases/download/v0.1.0/windows-x86_64.tar.gz"